### ISSUE TITLE
Crashes when picking a catwalk block.

### ISSUE THREAD

**Issue by gr4y** [thecodewarrior/Catwalks3#1]
Dear thecodewarrior,

Thanks for the mod, it is a really great alternative to vanilla fences and stairs :+1: I just found your mod on curse.com and I threw it in my mod folder and gave it a spin. I placed one Catwalk and added a Rope Light to it. When I wanted to pick it back up with my diamond pickaxe the game crashed on me, so here is the log: http://pastebin.com/q9A56bUG

**Comment by thecodewarrior** [comment]
Thanks, I haven't had this problem, but I think I know what it is. Is it reproducible? Does it happen every time? If it does, see if this fixes it. https://a.uguu.se/kakfhw_Catwalks-0.1.0-particleCrashFix.jar

**Comment by gr4y** [comment]
It is reproducable and I am sorry, but it even crashes when I replace the .jar with the particleCrashFix one. :(

**Comment by gr4y** [comment]
I was just looking at your build.gradle and saw that you are using the recommended forge release 1.8.9 - 11.15.1.1722 and I am playing with 1.8.9 - 11.15.1.1808. Maybe that's a issue with 1808?

**Comment by thecodewarrior** [comment]
Nope, here's a build so it'll yell if something tries to get the particle texture of the smart model instead of the actual model. If that's the problem we should find out who to yell at. :)

https://a.uguu.se/tgqlur_catwalks-0.1.0-nowitllyell.jar

**Comment by gr4y** [comment]
Here you go: http://pastebin.com/GVWd2NxV :grin: According to the stacktrace we are going to yell hat Mojang?

**Comment by thecodewarrior** [comment]
Sorry, I forgot to let you know that I made it so it returns the missing texture instead of null. That should definitely work.

It'll be in the next version. I should be able to get it out within a week if all goes to plan, if it isn't out by then I'll release a beta without proper textures.

**Comment by gr4y** [comment]
Take your time, mate. :smile:

**Comment by gr4y** [comment]
I just saw the bugfix release over on curse, so I gave it another try and it still does crash. I guess I can't report that bug to the caller, because Mojang ist he caller. :) http://pastebin.com/un1EedbN

**Comment by thecodewarrior** [comment]
Crap, I forgot I had it error there.

**Comment by thecodewarrior** [comment]
Closed as this is for an old version
