### ISSUE TITLE
(1.12) Poof! server crashes.

### ISSUE THREAD

**Issue by Migmag789** [thecodewarrior/Catwalks3#11]
Hi thecodewarrior ! My modpack crash only on server-side with your mod, using 3.0.3 version :/ can you fix this please ? :D 
[crash-2017-07-30_13.48.03-server.txt](https://github.com/thecodewarrior/Catwalks3/files/1185657/crash-2017-07-30_13.48.03-server.txt)

**Comment by thecodewarrior** [comment]
I just uploaded version 3.0.4 which fixes this. :)
