### ISSUE TITLE
Game Initialization Crash

### ISSUE THREAD

**Issue by kwstoudt** [thecodewarrior/Catwalks3#13]
My game keeps crashing while initializing. In order to stop the crashes, I have to disable this mod, which also causes me to disable another mod I have because of dependency.

Here is the error I get every time:
```
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: com.teamwizardry.librarianlib.features.kotlin.CommonUtilMethods.toNBT$default(Ljava/lang/Object;ZILjava/lang/Object;)Lnet/minecraft/nbt/NBTBase;
```
I have had this issue with both the current and last prior version of this mod.

Due to the number of mods I have installed, I have listed them in a pastebin paste: https://pastebin.com/E6zT2BcH

Also, here is my full crash report: https://pastebin.com/Dng1RHSp

**Comment by warplord** [comment]
Will this ever get fixed?

**Comment by thecodewarrior** [comment]
Catwalks 4 has been released, Catwalks 3 is no longer maintained.
