### ISSUE TITLE
Weird rendering with rusty/wooden stairs.

### ISSUE THREAD

**Issue by ghost** [thecodewarrior/Catwalks3#3]
also for some reason Java is searching for catwalks.gui.CatwalksModConfGuiFactory.

built with gradle
repo cloned with git (of course)

also some of screenshots have F3 open

Screenshots:

http://imgur.com/a/VOe1A

**Comment by thecodewarrior** [comment]
I changed the texture map but haven't updated all the textures, so they render weird.

Also the gui factory thing is a derp on my part.

**Comment by ghost** [comment]
I thought so
