### ISSUE TITLE
3 minor issues

### ISSUE THREAD

**Issue by Octopork** [thecodewarrior/Catwalks3#6]
Sorry if you prefer these in multiple issues, these are just minor enough i thought i would just post them in one...

- LibrarianLib isn't in the mods dependencies, resulting in a crash rather than the missing dependency screen on game launch.   
- MCMod.info is still default causing your mod to show up as ExampleMod in some areas.  
- No sounds for walking on catwalks.

**Comment by thecodewarrior** [comment]
The first two are super simple, but I'll have to think about the third. Minecraft checks 0.2 blocks below the player to see what step sound to use, so I don't know if I can make them play step sounds.

**Comment by thecodewarrior** [comment]
Solved in Catwalks 3.0.3. Please re-download LibrarianLib as its code specified an incorrect version in the previous build.
