### ISSUE TITLE
Various Catwalk Block Issues

### ISSUE THREAD

**Issue by ChloeDawn** [thecodewarrior/Catwalks3#8]
- [x] Catwalks have no hardness
- [x] Catwalks sound like stone
- [x] Catwalks drop no item even when broken with a pickaxe
- [x] Catwalks have no localization

**Mod version:** [3.0.1](https://minecraft.curseforge.com/projects/catwalks-3/files/2451860)
**Forge version:** [1.12-14.21.1.2413](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12-14.21.1.2413/forge-1.12-14.21.1.2413-changelog.txt)

![Recording of issues](https://fat.gfycat.com/TotalCarefreeCatfish.gif)

I also just noticed that the actual block breaking deals no damage to the pickaxe? That might be normal behaviour for a block with no hardness though, I forget..

**Comment by thecodewarrior** [comment]
These are all fixed in v3.0.3. I should be able to release it in less than an hour

**Comment by thecodewarrior** [comment]
Solved in Catwalks 3.0.3. Please re-download LibrarianLib as its code specified an incorrect version in the previous build.
