### ISSUE TITLE
[1.12] Catwalks 3 appears to be causing a strange crash on load?

### ISSUE THREAD

**Issue by elucent** [thecodewarrior/Catwalks3#9]
Just updated Catwalks 3 to the latest version (at the time of writing this, 3.0.2) and I have found a strange crash that only appears when Catwalks 3 is enabled.

Log: https://gist.github.com/elucent/929e060e8f0b15cdb1a411b1bb3f5dda

The loading bar appears to wait on "Constructing Mods" briefly before near-immediately crashing. This could very likely be a cross-mod issue and thus be potentially not your fault and be difficult to track, but is there anything you're doing that could cause an issue like this?

EDIT: Also of note, this issue did not appear using the previous version of Catwalks with an identical modlist.

**Comment by thecodewarrior** [comment]
Yup, that's going to be resolved in 3.0.3. It's a missing semicolon in the dependency string.

**Comment by thecodewarrior** [comment]
Solved in Catwalks 3.0.3. Please re-download LibrarianLib as its code specified an incorrect version in the previous build.
